# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
# Disable cache for development
spring.thymeleaf.cache=false

# Server Configuration
server.port=8090

# Custom info
info.app.name=EMS API
info.app.version=1.0.0
info.app.description=Employee Management System REST API

# App custom
ems.app.name=IBM Employee Management System
ems.app.version=1.0.0

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/ibm-ems

# OR separately:
# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=emsdb

## H2 In-Memory Database
#spring.datasource.url=jdbc:h2:mem:emsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.platform=h2
#
## H2 Console (access at http://localhost:8090/h2-console)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.web-allow-others=false
#
## JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.defer-datasource-initialization=true
#
## Seed data from data.sql
#spring.sql.init.mode=always

# Logging
#logging.level.com.ibm.ems=DEBUG
#logging.level.org.springframework.web=INFO
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.info.title=EMS REST API
springdoc.info.version=1.0.0
springdoc.info.description=IBM Employee Management System REST API
springdoc.swagger-ui.customCssUrl=/swagger-dark.css

## Expose specific or all endpoints
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=health,info,metrics,env,beans,mappings
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.endpoint.info.enabled=true
management.endpoint.health.enabled=true

# Change actuator base path
#management.endpoints.web.base-path=/actuator

# Security credentials
#spring.security.user.name=admin
#spring.security.user.password=password

#Spring security options - 
#1. default creds - user password from the logs 
#2. define creds in application.properties 
#3. define creds in Security config class 
#4. use Spring security User auth with JWT - industry standard  


